trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: chmod +x gradlew
    displayName: 'Make gradlew executable'

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      options: '--info --stacktrace'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
